language: java
install: true
jdk: oraclejdk8
script: ./gradlew publish
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -fr $HOME/.gradle/caches/*/scripts/
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
env:
  global:
    - secure: X22FgvoJa20fOFJqs0me7ik1kRvCute3OT4dzW/BMJ/nYcfrng7Cp2r1CU0w7ADLpK1HBLpdyqTQAcQfObbQLxdDJsdEQI476XD0AmAP/HuJQzSEasRLqq71JTgH2BNs6/4fu8HEiS/iMHUyNz42bB7NfgPZRPqn6b2d7g7ebxbyLki6Wq4wkmbFPjNMaoi0vnjOTdLgiCOOx4J0x8x1J3MHPvJQHl7YVP5JTKSsxdW+zItzZ+/dsr99OyF0u7ajYoCv4gQqfIT7ZmM+fmX6qXns5y8E4OyvPLnUKaE/8MstkwMfTtKMRtny+B6HTxugRV48PjYUGbjarJ5SuT/v5iK1LmbbBfM4MWv1eiiNWgExo8oc3NM10bVYTcCKw/Luio9hSWYFlUt52iASqSQL8Agvi804ICVxvomzEnHZxb3vehrhVS7W97Z8+8WHU97+MUi0a+w1Ay+8NkXSat9UuP9yxaP/d0cNSLoetmAOaoaCV5Es3PQm5v5fRV3lyjwKb0XkCMiXncmTsev+OAkgLzJ4J71fLDMFkrYTHoLV4TUbZr3bvA3NgGKi+eqrUQTlURjcaOuoAUwaDXdj/TVlV2vZHiS8/6y9kcUwuKPWfGpSiD/ex+AkV9H5NK9MFzSr6ynHKTV01weEnb0g6DKxND3jvpfLX/Q8PPgjjhpJTAE=
    - secure: IGdVaaj4IKN7ivu6ZC4PpiXLU7b7i5YCvBqPKIcdK5SXzNA4U7avLti62GqX/3cphjfoklEAMYtPFyfroJjJCcUo3j1U2goOTCvTQGsbqWMDdVDov8J4Q1mFwsmAh4Et2wJo71vUu0HcgbXto1k667l52b3wncZO0yirA4NxL+UXLPMR7k5qiyUxJdVzLNeP+ioq7udlOKODhqRqo13Kt2rJHgge8zYjGJIM3SvSwsJem5rOxhiVMi6oZZ/Qt7edYjVXxbxQakaB0rKUaje8kFC7pnnARZxUt2tlw+1FtdRdoOAPu0cQZP1UCWFirAJAeTJ7i9JMHnD4T90MypqazHDv23fEkvEKd446uG4BRvWt6db0Kgjw/yonRD/7wY9NhmMQ+um/eAAp/9uZBRHzKwh/p8HncqfpeGavm5n5farMqJ5b0TAHOpaE6ivcA3mYDXJy6wQsl0E/f+zL6i/G2Tu+8RU3xzAHvUfLU5ccthDu+lLRgvnAtucPmeiE5IgjkLWb11BK1mXuWsDRipD7Ykv6uVATFYOI8x0qKfedNFgpIkIQTu4A9UfmQtSNdAqr95emizGN2CWBI/trq7ksMNoGOibEx0sd3de4h9tMYSHd9nh/MJJGgycihbF4LHyqdKfrNltb8Qm4QDnRYsW30TbbAnN+y2rDk0HcFZYYNCk=
